install.packages("Rcpp")
install.packages("RcppArmadillo")
install.packages("ggplot2")
install.packages("devtools")
install.packages("doParallel")
install.packages("mvtnorm")
install.packages("BVAR")
library(devtools)
find_rtools(T)
has_devel()
install_github("kthohr/BMR")
library(bvartools)
library(readr)
library(fpp2)
library(tseries)
library(ggplot2)
library(forecast)
library(zoo)
library(xts)
library(vars)
library(urca)
library(sandwich)
library(BMR)
set.seed(42)
library("BVAR")
mn <- bv_minnesota(
  lambda = bv_lambda(mode = 0.2, sd = 0.4, min = 0.0001, max = 5),
  alpha = bv_alpha(mode = 2), var = 1e07)
soc <- bv_soc(mode = 1, sd = 1, min = 1e-04 , max = 50)
sur <- bv_sur(mode = 1, sd = 1, min = 1e-04, max = 50)
priors <- bv_priors(hyper = "auto", mn = mn, soc = soc, sur = sur)
mh <- bv_metropolis(scale_hess = c(0.05, 0.0001, 0.0001),
                    adjust_acc = TRUE, acc_lower = 0.25, acc_upper = 0.45)
run <- bvar(Cmydata, lags = 1, n_draw = 15000, n_burn = 5000, n_thin = 1,
            priors = priors, mh = mh, verbose = TRUE)
summary(run)
print(run)
coef(run)
vcov(run)
plot(run, type = "dens",
     var_response = "Inflation", var_impulse = "Confidence Indicator")
fitted(run, type = "mean")
plot(residuals(run, type = "mean"), vars = c("y1", "y2"))
opt_irf <- bv_irf(horizon = 16, identification = TRUE)
irf(run) <- irf(run, opt_irf, conf_bands = c(0.05, 0.16))
plot(irf(run), area = TRUE,
     vars_impulse = c("y9"), vars_response = c("y4"))
predict(run) <- predict(run, horizon = 16, conf_bands = c(0.05, 0.16))
plot(predict(run), area = TRUE, t_back = 32,
     vars = c("y3"))     

